#!/bin/bash

# Unload HID
echo "" > UDC
sleep 1
rm -v /sys/kernel/config/usb_gadget/pihid/configs/pihidconf.1/hid.usb0
sleep 1

# Load ETH
modprobe g_ether

# reload dhcp
service dnsmasq restart

# Forward traffic to wlan0
echo "1" > /proc/sys/net/ipv4/ip_forward
iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE



