#!/bin/bash

# Unload ETH
rmmod g_ether
sleep 1

# Initial setup
modprobe libcomposite
cd /sys/kernel/config/usb_gadget/
mkdir -p pihid
cd pihid

# Device description
echo 0x1d6b > idVendor # Linux Foundation
echo 0x0104 > idProduct # Multifunction Composite Gadget
echo 0x0666 > bcdDevice # Version
echo 0x0200 > bcdUSB # USB2
mkdir -p strings/0x409
echo "6666666666666666" > strings/0x409/serialnumber
echo "Foo" > strings/0x409/manufacturer
echo "Bar" > strings/0x409/product

# Define a keyboard
mkdir -p functions/hid.usb0
echo 1 > functions/hid.usb0/protocol # Keyboard
echo 1 > functions/hid.usb0/subclass # Boot Interface Subclass
echo 8 > functions/hid.usb0/report_length # 8 byte input
echo -ne \\x05\\x01\\x09\\x06\\xa1\\x01\\x05\\x07\\x19\\xe0\\x29\\xe7\\x15\\x00\\x25\\x01\\x75\\x01\\x95\\x08\\x81\\x02\\x95\\x01\\x75\\x08\\x81\\x03\\x95\\x06\\x75\\x08\\x15\\x00\\x25\\x65\\x05\\x07\\x19\\x00\\x29\\x65\\x81\\x00\\xc0 > functions/hid.usb0/report_desc
mkdir -p configs/pihidconf.1
ln -s functions/hid.usb0 configs/pihidconf.1/
echo 300 > configs/pihidconf.1/MaxPower

# Load HID
ls /sys/class/udc > UDC
chmod 777 /dev/hidg0